version: '3'
services:
  staking:
    env_file: .env
    networks:
      - ergo-offchain-execution_net
    build:
      context: .
      dockerfile: ./staking/Dockerfile
    volumes:
      - ./:/code
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
networks:
  ergo-offchain-execution_net:
    external: true
