version: '3'
services:
  staking:
      env_file: .env
      networks:
        - ergo-offchain-execution_net
      build:
        context: .
        dockerfile: ./staking/Dockerfile
      volumes:
        - ./:/code
      entrypoint: watchmedo auto-restart --recursive --pattern="*.py" --directory="./staking" -- python -m staking
      deploy:
        resources:
          limits:
            memory: 512M
networks:
  ergo-offchain-execution_net:
    external: true